language: node_js

node_js:
  - "9.4.0"

env:
  global:
    -

services:
  - mysql

before_install:
  - mysql -u root --password="" < test_schema.sql

install:
  - npm install
  - cd frontend/ && npm install && cd ..

addons:
  chrome: stable

script:
  - cd frontend/ && npm run build && cd ..
  - export NODE_ENV=TEST
  - node server.js &
  - npm run test

sudo: required
