language: node_js

node_js:
  - "9.4.0"

env:
  global:
    -

services:
  - mysql
  - docker

before_install:
  - mysql -u root --password="" < test_schema.sql
  - sudo docker build -t olinfse/strolle .
  - sudo docker run -d -p 3000:3000 -d olinfse/strolle
  - sudo docker run olinfse/strolle /bin/bash -c "npm run test"

addons:
  chrome: stable

script:

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

sudo: required
