language: node_js

node_js:
  - "node"
  - "9.4.0"

env:
  global:
    -

services:
  - mysql

before_install:
  - mysql -u strolle_app --password="walk" < test_schema.sql

install:
  - npm install
  - cd frontend/ && npm install && cd ..
