version: '3'
services:
    database:
        image: mysql
        container_name: "DB1.dev"
        volumes:
         - ./DB_STUFF:/docker-entrypoint-initdb.d
        environment:
          MYSQL_DATABASE: "strolle_test"
          MYSQL_USER: "strolle_app_test"
          MYSQL_PASSWORD: "walk"
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
         - "3306:3306"
    web:
        build: .
        ports:
         - "3000:3000"
